### ISSUE TITLE
minta projectnya

### ISSUE THREAD

**Issue by wibi9424** [rioastamal/quran-text#2]
bang aku mau pake project alquran ini buat web ku boleh gk, buat pribadi doang bang?, mungkin nanti ku upload ku web juga, tapi ntah bakal ada yg buka apa nggak.

**Comment by rioastamal** [comment]
Silahkan, mungkin bisa cek project [quran-json](https://github.com/rioastamal/quran-json) jika ingin dalam format JSON.
